config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "flat_bookings#home"
  resources :flat_bookings do
  	post :get_report, on: :collection
  	get :show_data, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat_booking.rb
class FlatBooking < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flat_bookings_controller.rb
class FlatBookingsController < ApplicationController
  def home

  end
	def get_report
    @results = []
    @start_date = DateTime.parse(params["flat_booking"]["start_date(1i)"] + "-" + params["flat_booking"]["start_date(2i)"] + "-" + params["flat_booking"]["start_date(3i)"])
    @end_date = DateTime.parse(params["flat_booking"]["end_date(1i)"] + "-" + params["flat_booking"]["end_date(2i)"] + "-" + params["flat_booking"]["end_date(3i)"])
    
    flats = FlatBooking.where("date_of_booking < ? AND date_of_booking >= ?", @end_date, @start_date)
    
    if params["flat_booking"]["report_type"] == "monthly_sales"
      flats.group_by {|e| e.date_of_booking.strftime('%Y-%b')}
    .each{|k,v| @results << {"#{k}" => v.inject(0){|sum,x| sum + (x.agreement_amount + (x.area * x.base_price))} }}
    else
      flats.group_by {|e| e.date_of_booking.strftime('%Y')}
    .each{|k,v| @results << {"#{k}" => v.inject(0){|sum,x| sum + (x.agreement_amount + (x.area * x.base_price))} }}
    end
    redirect_to action: 'show_data', results: @results
  end

  def show_data
    @results = params[:results]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flat_bookings_helper.rb
module FlatBookingsHelper
end

app/views/flat_bookings/get_report.html.erb
<%= @results.each do |u| %>
  <%= u %>
<% end %>

app/views/flat_bookings/home.html.erb
<%= simple_form_for :flat_booking, url: get_report_flat_bookings_path, remote: true do |f| %>
  <%= f.label :start_date %>
  <%= f.input :start_date, as: :date, label: false, presence: true %>
  <br>
  <%= f.label :end_date %>
  <%= f.input :end_date, as: :date, label: false, presence: true %>
  <br>
  <%= f.label :report_type %>
  <br>
  <%= f.select :report_type, ["monthly_sales", "yearly_sales"] %>
  <br>
  <br>
  <%= f.submit 'get data' %>
<% end %>

app/views/flat_bookings/show_data.html.erb
<% if @results.present? %>
<% @results.each do |r| %>
<%= r %>
<% end %>
<% else %>
No Data
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentOct16</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>